# Reference:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://cirrus-ci.org/guide/linux/
#   - https://cirrus-ci.org/guide/macOS/
#   - https://cirrus-ci.org/guide/windows/
#   - https://hub.docker.com/_/gcc/
#   - https://hub.docker.com/_/python/

#
# Global defaults.
#
container:
  image: python:3.9

env:
  # Maximum cache period (in weeks) before forcing a new cache upload.
  CACHE_PERIOD: "2"

#
# Testing (Linux)
#
linux_task:
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.9"
  name: "Linux: py${PY_VER}"
  container:
    image: gcc:latest
  env:
    PATH: $HOME/miniconda3/bin/:$PATH
  test_script:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b
    - conda install pytest numpy matplotlib
    - conda list
    - python setup.py install
    - pytest


#
# Testing (Windows)
#
windows_task:
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.9"
  name: "Windows: py${PY_VER}"
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    CIRRUS_SHELL: powershell
  env:
    PATH: $HOME\miniconda3\Library\bin;$PATH
  test_script:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -O miniconda.exe
    - Get-ChildItem -Path $HOME
    - .\miniconda.exe /S /D=$HOME\miniconda3 /RegisterPython=1 /InstallationType=JustMe /AddToPath=1 
    - Get-ChildItem -Path $HOME
    - Get-ChildItem -Path $HOME\miniconda3\Library\bin
    - conda install pytest numpy matplotlib
    - conda list
    - python setup.py install
    - pytest
