# Reference:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://cirrus-ci.org/guide/linux/
#   - https://cirrus-ci.org/guide/macOS/
#   - https://cirrus-ci.org/guide/windows/
#   - https://hub.docker.com/_/gcc/
#   - https://hub.docker.com/_/python/

#
# Global defaults.
#
container:
  image: python:3.9

env:
  # Maximum cache period (in weeks) before forcing a new cache upload.
  CACHE_PERIOD: "2"

#
# Testing (Linux)
#
linux_task:
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.9"
  name: "Linux: py${PY_VER}"
  container:
    image: gcc:latest
  test_script:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b
    - echo $(ls -ltr)
    - echo $(ls -ltr "$HOME")
    - $HOME/miniconda3/bin/python setup.py install
    - pytest

